### ISSUE TITLE
Исключение в СписокОбъектовКонфигурации.СформироватьСписокОбъектов()

### ISSUE THREAD

**Issue by 1cgh** [oscript-library/v8storage#19]
В СписокОбъектовКонфигурации.СформироватьСписокОбъектов() есть проверка:
```
         Если Файл.ЭтоКаталог() Тогда
             Продолжить;
         КонецЕсли;
```
для каждого обрабатываемого элемента из массива путей.
При этом файла фактически на диске может не быть. И ЭтоКаталог() падает в исключение, так как ему требуется реально существующий файл.
Варианты решения:
1) Выпилить совсем эту проверку.
2) Обернуть в попытку. В случае исключения спамить в лог, только надо с уровнем определиться.
3) Как-то иначе определять, что файл - это каталог. По этому варианту у меня идей нет :)

**Comment by nixel2007** [comment]
3 - ФС.КаталогСуществует() ?

**Comment by 1cgh** [comment]
@nixel2007 не у канпуктера, но тоже не прокатит, я думаю. у меня есть массив путей, но самих файлов по этим путям нет. т.е. фактически с помощью фс нет способа проверить каталог это или нет. только косвенно по строке пути. по наличию расширения вроде в данном случае можно

**Comment by nixel2007** [comment]
Там просто вызывается две проверки. Если Файл.существует() и Файл.ЭтоКаталог()

**Comment by 1cgh** [comment]
ну вот нет файлов, там где скрипт выполняется. только строки-пути)

**Comment by 1cgh** [comment]
еще как вариант добавить в метод параметр-флаг, отключающий проверку на каталог

**Comment by nixel2007** [comment]
@1cgh я что-то проблемы не понимаю. Ну нет файлов, есть строка... Почему нельзя сделать Новый Файл(ТвояСтрока).Существует? ФС в себя тоже строки, а не файлы, принимает

**Comment by 1cgh** [comment]
@nixel2007 метод работает с массивом путей. строк. это пути где-то, а не там где запущен скрипт, использующий метод. поэтому любые проверки, использующие обращение к файловой системе не корректны. строка-путь <> реальный файл/каталог

**Comment by 1cgh** [comment]
@nixel2007 ну т.е. представь, что массив путей я тебе просто в текстовом файлике прислал как строки. есть у тебя файлы на диске? что тебе скажут о них методы файловой системы? сможешь ты с помощью методов ФС понять, что очередной путь - это путь к каталогу?

@khorevaa в общем я предлагаю вместо ЭтоКаталог проверять наличие расширения. проверю только, что в штатной выгрузке все файлы имеют расширения, и PёRну

**Comment by khorevaa** [comment]
Исправлено
