### ISSUE TITLE
СконвертироватьОтчет публичный интерфейс

### ISSUE THREAD

**Issue by yehorh** [oscript-library/v8storage#23]
https://github.com/khorevaa/v8storage/blob/f4c7017cbc002280da3f801f3fdbc4a273a08ba1/features/step_definitions/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%D0%9E%D1%82%D1%87%D0%B5%D1%82%D0%B0%D0%98%D0%B7%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0.os#L67

В тестах вижу, в README.md публичном интерфейсе вижу.
А в реальности в коде нет.
Это в планах реализовать или я не там смотрю?

**Comment by HardAndHeavy** [comment]
Думаю, как вариант, можно пользоваться методом ХранилищеКонфигурации.ПолучитьТаблицуВерсийХранилища. Или как-то доработать этот метод [./src/Классы/internal/ripper/Классы/ПарсерОтчетаХранилища.os](https://github.com/khorevaa/v8storage/blob/f4c7017cbc/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/internal/ripper/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D0%B0%D1%80%D1%81%D0%B5%D1%80%D0%9E%D1%82%D1%87%D0%B5%D1%82%D0%B0%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0.os)

**Comment by khorevaa** [comment]
https://github.com/khorevaa/v8storage/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8.os#L559

не то?

**Comment by HardAndHeavy** [comment]
Я думаю yehorh говорит про json, а метод ПолучитьОтчетПоВерсиям формирует mxl файл. Сам думал о json, т.к. mxl сложно структурирован, а json вроде как заявлен был в описании. Потом пригляделся, а уже всё давно сделано, и на основе отчёта mxl формируется удобочитаемая таблица (ПолучитьТаблицуВерсийХранилища). Надобность в json отпала, лишь сложность в README нет описания что есть такой метод.

**Comment by khorevaa** [comment]
Реадми чутка усттарел.... есть желание дополнить. Жду ПР.
