### ISSUE TITLE
Работа с хранилищем расширения конфигурации 8.3.12

### ISSUE THREAD

**Issue by Berckk** [oscript-library/v8storage#4]
Предлагаю метод 

> Процедура УстановитьРасширениеХранилища(Знач НовоеИмяРасширения = "") Экспорт
> 
> ИмяРасширения = НовоеИмяРасширения;
> 
> КонецПроцедуры

**Comment by khorevaa** [comment]
Можно делай PR. Тесты не забудь в .feature

**Comment by Berckk** [comment]
Хорошо, займусь в ближайшее время.

**Comment by khorevaa** [comment]
@Berckk Надо вставить обязательно проверку на версию платформы т.к. с расширениями может работать только 8.3.12
